name: Test_suffix_tree
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    container:
      image: docker://srzzumix/googletest:latest
    steps:
    - name: your build and test
      run: |
        make test
