name: Test_suffix_tree
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    container:
      image: docker://srzzumix/googletest:latest
    steps:
    - uses: actions/checkout@v2
    - name: building
      run: |
        make test
        apt update
        apt install clang-format -y
    - uses: actions/checkout@v2
    - name: testing
      run: |
        make run_test
    - uses: actions/checkout@v2
    - name: formatting
      run: |
        make format
