name: Test_suffix_tree
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    container:
      image: docker://google/test
    steps:
    - uses: ./.github/actions/a
    - name: your build and test
      run: |
        make test
